/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.*;

/**
 *
 * @author palsa
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    Person prsn;
    Address prsnAddr;
    Driver drv;
    VhclReg vehReg;
    Patient pat;
    Doctor doc;
    Insurance insCov;
    
    public ReportJPanel(Person prsn, Address prsnAddr,Driver drv, VhclReg vehReg, Patient pat, Doctor doc, Insurance insCov ) {
        initComponents();
        this.prsn=prsn;
        this.prsnAddr=prsnAddr;
        this.doc=doc;
        this.drv=drv;
        this.pat=pat;
        this.vehReg=vehReg;
        this.insCov=insCov;
        displayReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbPrsnDtl = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        lbWebUrl = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbAddrDtl = new javax.swing.JLabel();
        lbLoc = new javax.swing.JLabel();
        lbCity = new javax.swing.JLabel();
        lbState = new javax.swing.JLabel();
        lbCountry = new javax.swing.JLabel();
        lbSsn = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtWebUrl = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lbAge = new javax.swing.JLabel();
        txtNat = new javax.swing.JTextField();
        lbNat = new javax.swing.JLabel();
        lbDob = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        lbDrvVhclReg = new javax.swing.JLabel();
        lbLicense = new javax.swing.JLabel();
        lbModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        lbSerial = new javax.swing.JLabel();
        lbYear = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        lbAddrDtl2 = new javax.swing.JLabel();
        lbDocId = new javax.swing.JLabel();
        txtDocId = new javax.swing.JTextField();
        txtDocPhone = new javax.swing.JTextField();
        lbDocAddr = new javax.swing.JLabel();
        lbDocPhone = new javax.swing.JLabel();
        txtDocSpec = new javax.swing.JTextField();
        lbDocSpec = new javax.swing.JLabel();
        lbDocName = new javax.swing.JLabel();
        txtDocName = new javax.swing.JTextField();
        lbDocDeg = new javax.swing.JLabel();
        txtDocDeg = new javax.swing.JTextField();
        lbDocEmail = new javax.swing.JLabel();
        txtDocEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDocAddr = new javax.swing.JTextArea();
        txtGender = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbAddrDtl3 = new javax.swing.JLabel();
        lbPatId = new javax.swing.JLabel();
        lbPrimDoc = new javax.swing.JLabel();
        txtPrimDoc = new javax.swing.JTextField();
        txtLastVst = new javax.swing.JTextField();
        txtNextVst = new javax.swing.JTextField();
        lbLastVst = new javax.swing.JLabel();
        lbNextVst = new javax.swing.JLabel();
        txtPatId = new javax.swing.JTextField();
        lbAllergy = new javax.swing.JLabel();
        lbMed = new javax.swing.JLabel();
        lbInsDtl = new javax.swing.JLabel();
        lbCompId = new javax.swing.JLabel();
        lbInsAddress = new javax.swing.JLabel();
        txtCompId = new javax.swing.JTextField();
        lbPremium = new javax.swing.JLabel();
        txtPremium = new javax.swing.JTextField();
        lbDed = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInsAddress = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBenefit = new javax.swing.JTextArea();
        lbBenefit = new javax.swing.JLabel();
        txtAllergy = new javax.swing.JTextField();
        txtMed = new javax.swing.JTextField();
        txtInsDed = new javax.swing.JTextField();
        lbAllergy1 = new javax.swing.JLabel();
        txtInsCov = new javax.swing.JTextField();
        txtPic = new javax.swing.JTextField();

        setBackground(new java.awt.Color(179, 208, 231));
        setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Patient Report");

        lbPrsnDtl.setBackground(new java.awt.Color(102, 153, 255));
        lbPrsnDtl.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lbPrsnDtl.setText("Patient's personal information");
        lbPrsnDtl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbName.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbName.setText("Name: ");

        lbPhone.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbPhone.setText("Phone:");

        lbWebUrl.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbWebUrl.setText("Website URL:");

        lbGender.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbGender.setText("Gender:");

        lbEmail.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbEmail.setText("Email:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbAddrDtl.setBackground(new java.awt.Color(153, 153, 255));
        lbAddrDtl.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lbAddrDtl.setText("Address Details");
        lbAddrDtl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbLoc.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbLoc.setText("GPS Location:");

        lbCity.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbCity.setText("City: ");

        lbState.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbState.setText("State: ");

        lbCountry.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbCountry.setText("Country: ");

        lbSsn.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbSsn.setText("SSN:");

        txtFullName.setEditable(false);
        txtFullName.setBackground(new java.awt.Color(179, 208, 231));
        txtFullName.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtFullName.setToolTipText("");
        txtFullName.setBorder(null);
        txtFullName.setOpaque(true);

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(179, 208, 231));
        txtPhone.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtPhone.setToolTipText("");
        txtPhone.setBorder(null);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        txtWebUrl.setEditable(false);
        txtWebUrl.setBackground(new java.awt.Color(179, 208, 231));
        txtWebUrl.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtWebUrl.setToolTipText("");
        txtWebUrl.setBorder(null);
        txtWebUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWebUrlActionPerformed(evt);
            }
        });

        txtSsn.setEditable(false);
        txtSsn.setBackground(new java.awt.Color(179, 208, 231));
        txtSsn.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtSsn.setToolTipText("");
        txtSsn.setBorder(null);
        txtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsnActionPerformed(evt);
            }
        });

        txtLoc.setEditable(false);
        txtLoc.setBackground(new java.awt.Color(179, 208, 231));
        txtLoc.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtLoc.setToolTipText("");
        txtLoc.setBorder(null);
        txtLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocActionPerformed(evt);
            }
        });

        txtCity.setEditable(false);
        txtCity.setBackground(new java.awt.Color(179, 208, 231));
        txtCity.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtCity.setToolTipText("");
        txtCity.setBorder(null);
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtState.setEditable(false);
        txtState.setBackground(new java.awt.Color(179, 208, 231));
        txtState.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtState.setToolTipText("");
        txtState.setBorder(null);
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        txtCountry.setEditable(false);
        txtCountry.setBackground(new java.awt.Color(179, 208, 231));
        txtCountry.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtCountry.setToolTipText("");
        txtCountry.setBorder(null);
        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(179, 208, 231));
        txtAge.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtAge.setToolTipText("");
        txtAge.setBorder(null);

        lbAge.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbAge.setText("Age:");

        txtNat.setEditable(false);
        txtNat.setBackground(new java.awt.Color(179, 208, 231));
        txtNat.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtNat.setToolTipText("");
        txtNat.setBorder(null);

        lbNat.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbNat.setText("Nationality: ");

        lbDob.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDob.setText("DOB:");

        txtDob.setEditable(false);
        txtDob.setBackground(new java.awt.Color(179, 208, 231));
        txtDob.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDob.setToolTipText("");
        txtDob.setBorder(null);

        lbDrvVhclReg.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lbDrvVhclReg.setText("Driver and Vehicle registration Details");
        lbDrvVhclReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbLicense.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbLicense.setText("License:");

        lbModel.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbModel.setText("Model:");

        txtModel.setEditable(false);
        txtModel.setBackground(new java.awt.Color(179, 208, 231));
        txtModel.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtModel.setToolTipText("");
        txtModel.setBorder(null);
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtSerial.setEditable(false);
        txtSerial.setBackground(new java.awt.Color(179, 208, 231));
        txtSerial.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtSerial.setToolTipText("");
        txtSerial.setBorder(null);
        txtSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialActionPerformed(evt);
            }
        });

        txtYear.setEditable(false);
        txtYear.setBackground(new java.awt.Color(179, 208, 231));
        txtYear.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtYear.setToolTipText("");
        txtYear.setBorder(null);
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        lbSerial.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbSerial.setText("Serial:");

        lbYear.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbYear.setText("Year:");

        txtLicense.setEditable(false);
        txtLicense.setBackground(new java.awt.Color(179, 208, 231));
        txtLicense.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtLicense.setToolTipText("");
        txtLicense.setBorder(null);
        txtLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseActionPerformed(evt);
            }
        });

        lbAddrDtl2.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lbAddrDtl2.setText("Doctor's Details");
        lbAddrDtl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbDocId.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDocId.setText("ID #:");

        txtDocId.setEditable(false);
        txtDocId.setBackground(new java.awt.Color(179, 208, 231));
        txtDocId.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDocId.setToolTipText("");
        txtDocId.setBorder(null);
        txtDocId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocIdActionPerformed(evt);
            }
        });

        txtDocPhone.setEditable(false);
        txtDocPhone.setBackground(new java.awt.Color(179, 208, 231));
        txtDocPhone.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDocPhone.setToolTipText("");
        txtDocPhone.setBorder(null);
        txtDocPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocPhoneActionPerformed(evt);
            }
        });

        lbDocAddr.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDocAddr.setText("Office Address:");

        lbDocPhone.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDocPhone.setText("Phone:");

        txtDocSpec.setEditable(false);
        txtDocSpec.setBackground(new java.awt.Color(179, 208, 231));
        txtDocSpec.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDocSpec.setToolTipText("");
        txtDocSpec.setBorder(null);
        txtDocSpec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocSpecActionPerformed(evt);
            }
        });

        lbDocSpec.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDocSpec.setText("Speciality: ");

        lbDocName.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDocName.setText("Name:");

        txtDocName.setEditable(false);
        txtDocName.setBackground(new java.awt.Color(179, 208, 231));
        txtDocName.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDocName.setToolTipText("");
        txtDocName.setBorder(null);
        txtDocName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocNameActionPerformed(evt);
            }
        });

        lbDocDeg.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDocDeg.setText("Degree:");

        txtDocDeg.setEditable(false);
        txtDocDeg.setBackground(new java.awt.Color(179, 208, 231));
        txtDocDeg.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDocDeg.setToolTipText("");
        txtDocDeg.setBorder(null);
        txtDocDeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocDegActionPerformed(evt);
            }
        });

        lbDocEmail.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDocEmail.setText("Email:");

        txtDocEmail.setEditable(false);
        txtDocEmail.setBackground(new java.awt.Color(179, 208, 231));
        txtDocEmail.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDocEmail.setToolTipText("");
        txtDocEmail.setBorder(null);
        txtDocEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocEmailActionPerformed(evt);
            }
        });

        txtDocAddr.setEditable(false);
        txtDocAddr.setBackground(new java.awt.Color(179, 208, 231));
        txtDocAddr.setColumns(20);
        txtDocAddr.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtDocAddr.setRows(5);
        jScrollPane1.setViewportView(txtDocAddr);

        txtGender.setEditable(false);
        txtGender.setBackground(new java.awt.Color(179, 208, 231));
        txtGender.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtGender.setToolTipText("");
        txtGender.setBorder(null);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(179, 208, 231));
        txtEmail.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtEmail.setToolTipText("");
        txtEmail.setBorder(null);

        lbAddrDtl3.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lbAddrDtl3.setText("Other Details");
        lbAddrDtl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPatId.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbPatId.setText("Patient Id#:");

        lbPrimDoc.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbPrimDoc.setText("Primary Doctor:");

        txtPrimDoc.setEditable(false);
        txtPrimDoc.setBackground(new java.awt.Color(179, 208, 231));
        txtPrimDoc.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtPrimDoc.setToolTipText("");
        txtPrimDoc.setBorder(null);
        txtPrimDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimDocActionPerformed(evt);
            }
        });

        txtLastVst.setEditable(false);
        txtLastVst.setBackground(new java.awt.Color(179, 208, 231));
        txtLastVst.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtLastVst.setToolTipText("");
        txtLastVst.setBorder(null);
        txtLastVst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastVstActionPerformed(evt);
            }
        });

        txtNextVst.setEditable(false);
        txtNextVst.setBackground(new java.awt.Color(179, 208, 231));
        txtNextVst.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtNextVst.setToolTipText("");
        txtNextVst.setBorder(null);
        txtNextVst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextVstActionPerformed(evt);
            }
        });

        lbLastVst.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbLastVst.setText("Last Visit:");

        lbNextVst.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbNextVst.setText("Next Visit:");

        txtPatId.setEditable(false);
        txtPatId.setBackground(new java.awt.Color(179, 208, 231));
        txtPatId.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtPatId.setToolTipText("");
        txtPatId.setBorder(null);
        txtPatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatIdActionPerformed(evt);
            }
        });

        lbAllergy.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbAllergy.setText("Allergy:");

        lbMed.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbMed.setText("On Medication:");

        lbInsDtl.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lbInsDtl.setText("Insurance Details");
        lbInsDtl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCompId.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbCompId.setText("Company Id#:");

        lbInsAddress.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbInsAddress.setText("Address:");

        txtCompId.setEditable(false);
        txtCompId.setBackground(new java.awt.Color(179, 208, 231));
        txtCompId.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtCompId.setToolTipText("");
        txtCompId.setBorder(null);
        txtCompId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompIdActionPerformed(evt);
            }
        });

        lbPremium.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbPremium.setText("Premium:");

        txtPremium.setEditable(false);
        txtPremium.setBackground(new java.awt.Color(179, 208, 231));
        txtPremium.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtPremium.setToolTipText("");
        txtPremium.setBorder(null);
        txtPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPremiumActionPerformed(evt);
            }
        });

        lbDed.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbDed.setText("Deductible:");

        txtInsAddress.setEditable(false);
        txtInsAddress.setBackground(new java.awt.Color(179, 208, 231));
        txtInsAddress.setColumns(20);
        txtInsAddress.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtInsAddress.setRows(5);
        jScrollPane2.setViewportView(txtInsAddress);

        txtBenefit.setEditable(false);
        txtBenefit.setBackground(new java.awt.Color(179, 208, 231));
        txtBenefit.setColumns(20);
        txtBenefit.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtBenefit.setRows(5);
        jScrollPane3.setViewportView(txtBenefit);

        lbBenefit.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbBenefit.setText("Benefits:");

        txtAllergy.setEditable(false);
        txtAllergy.setBackground(new java.awt.Color(179, 208, 231));
        txtAllergy.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtAllergy.setToolTipText("");
        txtAllergy.setBorder(null);
        txtAllergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergyActionPerformed(evt);
            }
        });

        txtMed.setEditable(false);
        txtMed.setBackground(new java.awt.Color(179, 208, 231));
        txtMed.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtMed.setToolTipText("");
        txtMed.setBorder(null);
        txtMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedActionPerformed(evt);
            }
        });

        txtInsDed.setEditable(false);
        txtInsDed.setBackground(new java.awt.Color(179, 208, 231));
        txtInsDed.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtInsDed.setToolTipText("");
        txtInsDed.setBorder(null);
        txtInsDed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsDedActionPerformed(evt);
            }
        });

        lbAllergy1.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lbAllergy1.setText("Is Patient Insured:");

        txtInsCov.setEditable(false);
        txtInsCov.setBackground(new java.awt.Color(179, 208, 231));
        txtInsCov.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        txtInsCov.setToolTipText("");
        txtInsCov.setBorder(null);
        txtInsCov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsCovActionPerformed(evt);
            }
        });

        txtPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPrimDoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrimDoc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPatId)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLastVst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastVst)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbNextVst)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNextVst))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMed, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSsn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSsn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPremium)
                                .addGap(12, 12, 12)
                                .addComponent(txtPremium)
                                .addGap(18, 18, 18)
                                .addComponent(lbDed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInsDed)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCompId)
                                .addGap(12, 12, 12)
                                .addComponent(txtCompId))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAddrDtl3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbAllergy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAllergy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMed)
                                        .addGap(129, 129, 129))
                                    .addComponent(lbPrsnDtl, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbWebUrl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWebUrl)
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbEmail)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtEmail)
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFullName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbGender)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(txtNat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lbPhone))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtGender)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lbAge)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lbDob))))
                                            .addComponent(lbNat))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDob)
                                            .addComponent(txtPhone)))
                                    .addComponent(lbInsDtl, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbAllergy1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInsCov)
                                        .addGap(159, 159, 159)))
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbBenefit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbInsAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDocName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDocName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDocId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDocId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDocSpec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDocSpec))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLicense)
                                    .addComponent(lbModel)
                                    .addComponent(lbSerial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtModel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbYear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtYear)
                                        .addGap(2, 2, 2))
                                    .addComponent(txtSerial, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLicense, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtPic, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbDocEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDocEmail))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbDocPhone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDocPhone))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbDocDeg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDocDeg))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbDocAddr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbLoc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLoc))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCity)
                                            .addComponent(lbState))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtState)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbCountry)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCountry))
                                            .addComponent(txtCity)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbAddrDtl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbAddrDtl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbDrvVhclReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(2, 2, 2)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbAddrDtl, lbAddrDtl2, lbAddrDtl3, lbDrvVhclReg, lbInsDtl, lbPrsnDtl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtPic, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAddrDtl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLoc)
                            .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbState)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCountry)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDrvVhclReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLicense)
                            .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbModel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbYear)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSerial)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lbAddrDtl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDocId)
                            .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDocName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDocSpec)
                            .addComponent(txtDocSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDocDeg)
                            .addComponent(txtDocDeg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDocAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDocPhone)
                            .addComponent(txtDocPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDocEmail)
                            .addComponent(txtDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPrsnDtl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGender)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDob)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNat)
                            .addComponent(txtNat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSsn))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbWebUrl)
                            .addComponent(txtWebUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAddrDtl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPatId)
                            .addComponent(txtPatId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrimDoc)
                            .addComponent(txtPrimDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLastVst)
                            .addComponent(txtLastVst, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNextVst)
                            .addComponent(txtNextVst, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbAllergy)
                                .addComponent(lbMed))
                            .addComponent(txtAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAllergy1)
                            .addComponent(txtInsCov, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbInsDtl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCompId)
                            .addComponent(txtCompId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbInsAddress)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbPremium))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbDed)
                                .addComponent(txtInsDed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBenefit)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFullName, txtGender, txtPhone, txtSsn, txtWebUrl});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCity, txtCountry, txtLoc, txtState});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbAddrDtl, lbAddrDtl2, lbAddrDtl3, lbDrvVhclReg, lbInsDtl, lbPrsnDtl});

    }// </editor-fold>//GEN-END:initComponents

    private void txtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsnActionPerformed

    private void txtWebUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWebUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWebUrlActionPerformed

    private void txtLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseActionPerformed

    private void txtDocIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocIdActionPerformed

    private void txtDocPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocPhoneActionPerformed

    private void txtDocSpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocSpecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocSpecActionPerformed

    private void txtDocNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocNameActionPerformed

    private void txtDocDegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocDegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocDegActionPerformed

    private void txtDocEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocEmailActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtPrimDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimDocActionPerformed

    private void txtLastVstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastVstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastVstActionPerformed

    private void txtNextVstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextVstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextVstActionPerformed

    private void txtPatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatIdActionPerformed

    private void txtCompIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompIdActionPerformed

    private void txtPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPremiumActionPerformed

    private void txtAllergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergyActionPerformed

    private void txtMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedActionPerformed

    private void txtInsDedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsDedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsDedActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtInsCovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsCovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsCovActionPerformed

    private void txtPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAddrDtl;
    private javax.swing.JLabel lbAddrDtl2;
    private javax.swing.JLabel lbAddrDtl3;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbAllergy;
    private javax.swing.JLabel lbAllergy1;
    private javax.swing.JLabel lbBenefit;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbCompId;
    private javax.swing.JLabel lbCountry;
    private javax.swing.JLabel lbDed;
    private javax.swing.JLabel lbDob;
    private javax.swing.JLabel lbDocAddr;
    private javax.swing.JLabel lbDocDeg;
    private javax.swing.JLabel lbDocEmail;
    private javax.swing.JLabel lbDocId;
    private javax.swing.JLabel lbDocName;
    private javax.swing.JLabel lbDocPhone;
    private javax.swing.JLabel lbDocSpec;
    private javax.swing.JLabel lbDrvVhclReg;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbInsAddress;
    private javax.swing.JLabel lbInsDtl;
    private javax.swing.JLabel lbLastVst;
    private javax.swing.JLabel lbLicense;
    private javax.swing.JLabel lbLoc;
    private javax.swing.JLabel lbMed;
    private javax.swing.JLabel lbModel;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNat;
    private javax.swing.JLabel lbNextVst;
    private javax.swing.JLabel lbPatId;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbPremium;
    private javax.swing.JLabel lbPrimDoc;
    private javax.swing.JLabel lbPrsnDtl;
    private javax.swing.JLabel lbSerial;
    private javax.swing.JLabel lbSsn;
    private javax.swing.JLabel lbState;
    private javax.swing.JLabel lbWebUrl;
    private javax.swing.JLabel lbYear;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergy;
    private javax.swing.JTextArea txtBenefit;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompId;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextArea txtDocAddr;
    private javax.swing.JTextField txtDocDeg;
    private javax.swing.JTextField txtDocEmail;
    private javax.swing.JTextField txtDocId;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtDocPhone;
    private javax.swing.JTextField txtDocSpec;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextArea txtInsAddress;
    private javax.swing.JTextField txtInsCov;
    private javax.swing.JTextField txtInsDed;
    private javax.swing.JTextField txtLastVst;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtMed;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNat;
    private javax.swing.JTextField txtNextVst;
    private javax.swing.JTextField txtPatId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPic;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtPrimDoc;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtWebUrl;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void displayReport() {
        
        
        txtFullName.setText(prsn.getName());
        txtAge.setText(String.valueOf(prsn.getAge()));
        txtGender.setText(prsn.getGender());
        txtDob.setText(prsn.getDob());
        txtNat.setText(prsn.getNationality());
        txtPhone.setText(prsn.getPhone());
        txtSsn.setText(prsn.getSsn());
        txtEmail.setText(prsn.getEmail());
        txtWebUrl.setText(prsn.getWebUrl());
        txtPic.setText(prsn.getPicture());
        
        txtPatId.setText(pat.getPatientId());
        txtPrimDoc.setText(pat.getDocName());
        txtLastVst.setText(pat.getLastVisit());
        txtNextVst.setText(pat.getNextvisit());
        txtAllergy.setText(pat.getAllergy());
        txtMed.setText(pat.getOnMedication());
        txtInsCov.setText(pat.getInsCov());
        
        txtCompId.setText(insCov.getC_id());
        txtInsAddress.setText(insCov.getInsAddr());
        txtPremium.setText(String.valueOf(insCov.getPremium()));
        txtInsDed.setText(String.valueOf(insCov.getDeductible()));
        txtBenefit.setText(insCov.getBenefit());
        
        txtLoc.setText(prsnAddr.getGps_lat()+""+prsnAddr.getGps_lon());
        txtCity.setText(prsnAddr.getCity());
        txtState.setText(prsnAddr.getState());
        txtCountry.setText(prsnAddr.getCountry());
        
        txtLicense.setText(drv.getLicense());
        txtModel.setText(vehReg.getModel());
        txtYear.setText(vehReg.getYear());
        txtSerial.setText(vehReg.getSerial());
        
        txtDocId.setText(doc.getDocId());
        txtDocName.setText(doc.getDocName());
        txtDocAddr.setText(doc.getOfcAddr());
        txtDocDeg.setText(doc.getDegree());
        txtDocEmail.setText(doc.getEmail());
        txtDocPhone.setText(doc.getPhone());
        txtDocSpec.setText(doc.getSpeciality());
        
        System.out.println("Patient's Personal Information");
        System.out.println("===============================");
        System.out.println("Name: "+prsn.getName());
        System.out.println("Age:"+String.valueOf(prsn.getAge()));
        System.out.println("Gender: "+prsn.getGender());
        System.out.println("Dob: "+prsn.getDob());
        System.out.println("Nationality: "+prsn.getNationality());
        System.out.println("Phone: "+prsn.getPhone());
        System.out.println("SSN:"+prsn.getSsn());
        System.out.println("Email: "+prsn.getEmail());
        System.out.println("Web URL: "+prsn.getWebUrl());
        System.out.println("Picture link :"+prsn.getPicture());
        System.out.println("===============================");
        
        System.out.println("Patient's Other Information");
        System.out.println("============================");
        System.out.println("Patient id :"+pat.getPatientId());
        System.out.println("Primary Doctor :"+pat.getDocName());
        System.out.println("Last Visit: "+pat.getLastVisit());
        System.out.println("Next Visit: "+pat.getNextvisit());
        System.out.println("Any Allergy: "+pat.getAllergy());
        System.out.println("Any Medication: "+pat.getOnMedication());
        System.out.println("Insurance Coverage: "+pat.getInsCov());
        System.out.println("===============================");
        
        System.out.println("Patient's Adddress Information");
        System.out.println("===============================");
        System.out.println("GPS Location: "+prsnAddr.getGps_lat()+" "+prsnAddr.getGps_lon());
        System.out.println("City: "+prsnAddr.getCity());
        System.out.println("State: "+prsnAddr.getState());
        System.out.println("Country: "+prsnAddr.getCountry());
        System.out.println("===============================");
        
        System.out.println("Doctor Details");
        System.out.println("===============================");
        System.out.println("ID: "+doc.getDocId());
        System.out.println("Name: "+doc.getDocName());
        System.out.println("Office Address: "+doc.getOfcAddr());
        System.out.println("Degree: "+doc.getDegree());
        System.out.println("Email: "+doc.getEmail());
        System.out.println("Phone: "+doc.getPhone());
        System.out.println("Speciality: "+doc.getSpeciality());
        System.out.println("===============================");
              
        System.out.println("Driver and Vehicle Details");
        System.out.println("===============================");
        System.out.println("License: "+drv.getLicense());
        System.out.println("Model: "+vehReg.getModel());
        System.out.println("Year: "+vehReg.getYear());
        System.out.println("Serial #:"+vehReg.getSerial());
        System.out.println("===============================");
        
        System.out.println("Insurnce Coverage Details");
        System.out.println("===============================");
        System.out.println("Company id: "+insCov.getC_id());
        System.out.println("Address: "+insCov.getInsAddr());
        System.out.println("Premium: "+String.valueOf(insCov.getPremium()));
        System.out.println("Deductible: "+String.valueOf(insCov.getDeductible()));
        System.out.println("Benefits:"+insCov.getBenefit());
        System.out.println("===============================");
        
        
        
        
        
        
        
        
                
        
        
       
    }
    
}
