/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.EmployerDirectory;
import Business.Profiles.FacultyDirectory;
import Business.Profiles.StudentDirectory;
import Business.Profiles.ThirdPartyDirectory;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anupb
 */
public class Register2JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Register2JPanel
     */
    JSplitPane splitPane;

    PersonDirectory personDirectory;
    UserAccountDirectory useraccountdirectory;
    StudentDirectory studentdirectory;
    FacultyDirectory facultydirectory;
    ThirdPartyDirectory thirdpartydirectory;
    EmployerDirectory employerdirectory;

    public Register2JPanel(JSplitPane splitPane, PersonDirectory personDirectory, UserAccountDirectory useraccountdirectory, FacultyDirectory facultydirectory, StudentDirectory studentdirectory,ThirdPartyDirectory thirdpartydirectory, EmployerDirectory employerdirectory) {
        initComponents();

        this.splitPane = splitPane;
        this.personDirectory = personDirectory;
        this.useraccountdirectory = useraccountdirectory;
        this.facultydirectory = facultydirectory;
        this.studentdirectory = studentdirectory;
        this.thirdpartydirectory=thirdpartydirectory;
        this.employerdirectory=employerdirectory;
        btnSave.setEnabled(false);
        viewdisplay();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtvSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lblRegion = new javax.swing.JLabel();
        txtDevice = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        lblDevice = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Region", "Country", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblView);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("VIEW PERSON");

        txtvSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Search ID");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblRegion.setText("Region");

        lblCountry.setText("Country");

        lblDevice.setText("Device");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblLanguage.setText("Language");

        lblEmail.setText("Email Id");

        lblId.setText("ID");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblAge.setText("Age");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lblGender.setText("Gender");

        txtRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegionActionPerformed(evt);
            }
        });

        lblAddress.setText("Address");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Person");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Person");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtvSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(284, 284, 284)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblId)
                                                .addComponent(lblName)
                                                .addComponent(lblAge)
                                                .addComponent(lblGender)
                                                .addComponent(lblAddress)
                                                .addComponent(lblRegion)
                                                .addComponent(lblCountry)
                                                .addComponent(lblDevice))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDevice)
                                                .addComponent(txtCountry)
                                                .addComponent(txtRegion)
                                                .addComponent(txtAddress)
                                                .addComponent(txtGender)
                                                .addComponent(txtAge)
                                                .addComponent(txtName)
                                                .addComponent(txtId)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblLanguage)
                                                .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                                .addComponent(txtEmail))))))
                            .addGap(33, 33, 33)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(215, 215, 215)
                            .addComponent(btnSave)
                            .addGap(28, 28, 28)
                            .addComponent(btnUpdate)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelete)
                            .addGap(18, 18, 18)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnSave, btnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDevice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLanguage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnBack))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtvSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvSearchActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, "Please Update the fields now!");

        txtId.setEditable(false);
        txtName.setEditable(true);
        txtAge.setEditable(true);
        txtGender.setEditable(true);
        txtAddress.setEditable(true);
        txtRegion.setEditable(true);
        txtCountry.setEditable(true);
        txtDevice.setEditable(true);
        txtLanguage.setEditable(true);
        txtEmail.setEditable(true);

        for (Person per : personDirectory.getPersonlist()) {

            if (per.getPersonId().equals(txtId.getText())) {

                String id = txtId.getText();
                String name = txtName.getText();
                String gender = txtGender.getText();
                int age = Integer.parseInt(txtAge.getText());
                String address = txtAddress.getText();
                String emailId = txtEmail.getText();
                String region = txtRegion.getText();
                String country = txtCountry.getText();
                String device = txtDevice.getText();
                String language = txtLanguage.getText();

                per.setPersonId(id);
                per.setName(name);
                per.setGender(gender);
                per.setAge(age);
                per.setAddress(address);
                per.setEmailId(emailId);
                per.setRegion(region);
                per.setCountry(country);
                per.setDevice(device);
                per.setLanguage(language);

            }
        }

        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);

        for (Person per : personDirectory.getPersonlist()) {

            Object[] info = new Object[5];
            info[0] = per;
            info[1] = per.getName();
            info[2] = per.getRegion();
            info[3] = per.getCountry();
            info[4] = per.getEmailId();

            model.addRow(info);

        }

        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblView.getSelectedRow();
        if (selectedRow >= 0) {

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the account details?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {

                Person per = (Person) tblView.getValueAt(selectedRow, 0);
                personDirectory.deletePerson(per);
                viewdisplay();

            }
        } else {

            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        if (!txtvSearch.getText().isEmpty()) {
            for (Person per : personDirectory.getPersonlist()) {

                if (per.getPersonId().equals(txtvSearch.getText())) {

                    txtId.setText(per.getPersonId());
                    txtName.setText(per.getName());
                    txtAge.setText(String.valueOf(per.getAge()));
                    txtGender.setText(per.getGender());
                    txtAddress.setText(per.getAddress());
                    txtRegion.setText(per.getRegion());
                    txtCountry.setText(per.getCountry());
                    txtDevice.setText(per.getDevice());
                    txtLanguage.setText(per.getLanguage());
                    txtEmail.setText(per.getEmailId());

                    txtId.setEditable(false);
                    txtName.setEditable(false);
                    txtAge.setEditable(false);
                    txtGender.setEditable(false);
                    txtAddress.setEditable(false);
                    txtRegion.setEditable(false);
                    txtCountry.setEditable(false);
                    txtDevice.setEditable(false);
                    txtLanguage.setEditable(false);
                    txtEmail.setEditable(false);

                }
            }
        } else {

            JOptionPane.showMessageDialog(this, "Please enter the id in search text");

        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        Register4JPanel rjpl4 = new Register4JPanel(splitPane, personDirectory, useraccountdirectory, facultydirectory, studentdirectory,thirdpartydirectory, employerdirectory);
        splitPane.setRightComponent(rjpl4);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (txtId.getText().isEmpty() || txtName.getText().isEmpty() || txtAge.getText().isEmpty() || txtGender.getText().isEmpty() || txtAddress.getText().isEmpty() || txtRegion.getText().isEmpty() || txtCountry.getText().isEmpty() || txtLanguage.getText().isEmpty() || txtEmail.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Field is empty");
        } else if (txtId.getText().matches("[a-z][A-Z]")) {

            JOptionPane.showMessageDialog(this, "Invalid ID");

        } else if (!txtAge.getText().matches("[1-9][0-9]")) {

            JOptionPane.showMessageDialog(this, "Invalid Age");

        } else if (!txtName.getText().matches("^[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(this, "Invalid Name");

        } else if (!(txtGender.getText().matches("Male") || txtGender.getText().matches("Female"))) {

            JOptionPane.showMessageDialog(this, "Please enter correct Gender");
        } else if (!txtRegion.getText().matches("^[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(this, "Invalid Region");

        } else if (!txtCountry.getText().matches("^[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(this, "Invalid Country");

        } else if (!txtLanguage.getText().matches("^[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(this, "Invalid Languague");

        } else if (!txtEmail.getText().matches("[a-zA-Z0-9]+@[a-z]+\\.edu")) {

            JOptionPane.showMessageDialog(this, "Please enter correct email id!");
        } else {

            JOptionPane.showMessageDialog(this, "Details have been saved!");

            txtId.setEditable(false);
            txtName.setEditable(false);
            txtAge.setEditable(false);
            txtGender.setEditable(false);
            txtAddress.setEditable(false);
            txtRegion.setEditable(false);
            txtCountry.setEditable(false);
            txtDevice.setEditable(false);
            txtLanguage.setEditable(false);
            txtEmail.setEditable(false);

            for (Person per : personDirectory.getPersonlist()) {

                if (per.getPersonId().equals(txtId.getText())) {

                    String id = txtId.getText();
                    String name = txtName.getText();
                    String gender = txtGender.getText();
                    int age = Integer.parseInt(txtAge.getText());
                    String address = txtAddress.getText();
                    String emailId = txtEmail.getText();
                    String region = txtRegion.getText();
                    String country = txtCountry.getText();
                    String device = txtDevice.getText();
                    String language = txtLanguage.getText();

                    per.setPersonId(id);
                    per.setName(name);
                    per.setGender(gender);
                    per.setAge(age);
                    per.setAddress(address);
                    per.setEmailId(emailId);
                    per.setRegion(region);
                    per.setCountry(country);
                    per.setDevice(device);
                    per.setLanguage(language);

                }
            }

            DefaultTableModel model = (DefaultTableModel) tblView.getModel();
            model.setRowCount(0);

            for (Person per : personDirectory.getPersonlist()) {

                Object[] info = new Object[5];
                info[0] = per;
                info[1] = per.getName();
                info[2] = per.getRegion();
                info[3] = per.getCountry();
                info[4] = per.getEmailId();

                model.addRow(info);

            }

            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDevice;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDevice;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtvSearch;
    // End of variables declaration//GEN-END:variables

    private void viewdisplay() {

        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);

        for (Person per : personDirectory.getPersonlist()) {

            Object[] info = new Object[5];
            info[0] = per;
            info[1] = per.getName();
            info[2] = per.getRegion();
            info[3] = per.getCountry();
            info[4] = per.getEmailId();

            model.addRow(info);

        }

    }
}
