/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.EmployerDirectory;
import Business.Profiles.FacultyDirectory;
import Business.Profiles.StudentDirectory;
import Business.Profiles.ThirdPartyDirectory;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author anupb
 */
public class UserAccount1JPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserAccount1JPanel
     */
    
    JSplitPane splitPane;    
    PersonDirectory personDirectory;
    UserAccountDirectory useraccountdirectory;
    StudentDirectory studentdirectory;
    FacultyDirectory facultydirectory;
    Person prsn;
    UserAccount userAcc;
    ThirdPartyDirectory thirdpartydirectory;
    EmployerDirectory employerdirectory;
    
    public UserAccount1JPanel(JSplitPane splitPane, PersonDirectory personDirectory,Person prsn , UserAccountDirectory useraccountdirectory, FacultyDirectory facultydirectory, StudentDirectory studentdirectory, UserAccount userAcc, ThirdPartyDirectory thirdpartydirectory, EmployerDirectory employerdirectory) {
        initComponents();
        
         this.splitPane = splitPane;
        this.personDirectory = personDirectory;
        this.useraccountdirectory=useraccountdirectory;
        this.facultydirectory=facultydirectory;
        this.studentdirectory=studentdirectory;
        this.prsn=prsn;
        this.userAcc = userAcc;
        this.thirdpartydirectory=thirdpartydirectory;
        this.employerdirectory=employerdirectory;
        
        txtName1.setText(userAcc.getPrsn().getName());
        txtId1.setText(userAcc.getPersonId());
        txtUsername.setText(userAcc.getUsername());
        txtPwd.setText(userAcc.getPassword());
        txtRole.setText(userAcc.getRole());
        txtStatus.setText(userAcc.getStatus());
        
        
        
        txtId1.setEditable(false);
        txtName1.setEditable(false);
        txtUsername.setEditable(false);
        txtPwd.setEditable(false);
        txtRole.setEditable(false);
        txtStatus.setEditable(true);
        
        btnSave.setEnabled(false);
        if(txtStatus.getText().equals("Disabled")){
        btnEnable.setEnabled(true);
        btnDisable.setEnabled(false);}
        else{
        btnEnable.setEnabled(false);
        btnDisable.setEnabled(true);
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        btnEnable = new javax.swing.JButton();
        btnDisable = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        txtRole = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPwd = new javax.swing.JTextField();
        lblId1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtId1 = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("MANAGE USER ACCOUNT");

        btnEnable.setText("Enable User Account");
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });

        btnDisable.setText("Disable User Account");
        btnDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableActionPerformed(evt);
            }
        });

        btnUpdateUser.setText("Update User Account");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        txtRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleActionPerformed(evt);
            }
        });

        lblUsername.setText("Username");

        lblPwd.setText("Password");

        lblProfile.setText("Role");

        lblStatus.setText("Status");

        lblId1.setText("ID");

        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        lblName1.setText("Name");

        btnSave.setText("Save User Account");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblName1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtName1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblId1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUsername)
                                        .addComponent(lblPwd)
                                        .addComponent(lblProfile)
                                        .addComponent(lblStatus))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsername)
                                        .addComponent(txtPwd)
                                        .addComponent(txtRole)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnEnable)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisable)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateUser)
                        .addGap(26, 26, 26)
                        .addComponent(btnBack)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblId1, lblName1, lblProfile, lblPwd, lblStatus, lblUsername});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDisable, btnEnable, btnSave});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnUpdateUser});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblId1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfile)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnSave)
                    .addComponent(btnDisable)
                    .addComponent(btnEnable))
                .addContainerGap(325, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblId1, lblName1, lblProfile, lblPwd, lblStatus, lblUsername, txtId1, txtName1, txtPwd, txtRole, txtStatus, txtUsername});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableActionPerformed
        // TODO add your handling code here:
        
        
        
      if(txtStatus.getText().equals("Disabled")){    
                    
        if(!txtId1.getText().equals("1")) {
        for (UserAccount ua : useraccountdirectory.getUserAccountList()){
        
             if(ua.getPersonId().equals(txtId1.getText())){
             
                String status = txtStatus.getText();
               // String pwd = txtPwd.getText();
                
                
                 ua.setStatus(status);
                 //ua.setPassword(pwd);
                
             
             
             }
        
        } 
        }
        
        else{
           
            JOptionPane.showMessageDialog(this, "You cannot change the status of ADMIN","Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }                                      
    
    
   if(!txtId1.getText().equals("1")){ 
    if(txtStatus.getText().equals("Disabled")){
        JOptionPane.showMessageDialog(this, "User has been blocked!");
        btnEnable.setEnabled(true);
        btnDisable.setEnabled(false);
    }
    else{
        JOptionPane.showMessageDialog(this, "Status incorrect - please change to Disabled to Block","Warning", JOptionPane.WARNING_MESSAGE); }
   } 
   
   else{
   
     JOptionPane.showMessageDialog(this, "Please Update the status of another user except ADMIN!");
   }
    
    
    
    }//GEN-LAST:event_btnDisableActionPerformed
    
    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Please Update the fields now!");
        
        btnSave.setEnabled(true);
        btnUpdateUser.setEnabled(false);
        
        txtId1.setEditable(false);
        txtName1.setEditable(false);
        txtUsername.setEditable(true);
        txtPwd.setEditable(true);
        txtStatus.setEditable(false);
        
        

        
        
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void txtRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
       
        
        btnSave.setEnabled(false);
        btnUpdateUser.setEnabled(true);
        
        txtUsername.setEditable(false);
        txtPwd.setEditable(false);
        
        
       if(!txtPwd.getText().matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$")){
                    
              JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one digit.", "Warning", JOptionPane.WARNING_MESSAGE);
             }
       else{ 
        for (UserAccount ua : useraccountdirectory.getUserAccountList()){
        
             if(ua.getPersonId().equals(txtId1.getText())){
             
                String username = txtUsername.getText();
                String pwd = txtPwd.getText();
                
                
                 ua.setUsername(username);
                 ua.setPassword(pwd);
                
               JOptionPane.showMessageDialog(this, "Details have been saved!");
             
             }
        
        }
       }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        
        UserAccount4JPanel uajpl4 = new UserAccount4JPanel(splitPane, personDirectory,prsn, useraccountdirectory, facultydirectory, studentdirectory, userAcc, thirdpartydirectory, employerdirectory);
        splitPane.setRightComponent(uajpl4);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
        // TODO add your handling code here:
        
      if(txtStatus.getText().equals("Enabled")){    
                    
        for (UserAccount ua : useraccountdirectory.getUserAccountList()){
        
             if(ua.getPersonId().equals(txtId1.getText())){
             
                String status = txtStatus.getText();
               // String pwd = txtPwd.getText();
                
                
                 ua.setStatus(status);
                 //ua.setPassword(pwd);
                
             
             
             }
        
        } 
    }
    
    
    if(txtStatus.getText().equals("Enabled")){
    JOptionPane.showMessageDialog(this, "User has been unblocked!");
    btnEnable.setEnabled(false);
    btnDisable.setEnabled(true);
    }
    else{
        JOptionPane.showMessageDialog(this, "Status incorrect - Please change to Enabled to UNBLOCK","Warning", JOptionPane.WARNING_MESSAGE);}
        
    }//GEN-LAST:event_btnEnableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDisable;
    private javax.swing.JButton btnEnable;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPwd;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
