/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Welcome;

import Business.Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Network.EnterpriseNetwork;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author palsa
 */
public class SignInJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignInJPanel
     */
        public EcoSystem system;
        //private JPanel WelcomeCard;
        private JSplitPane splitPane;   
    public SignInJPanel(JSplitPane splitPane, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        //system=EcoSystem.getInstance();
        this.system=system;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signinFormPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        separatorLine2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        separatorLine4 = new javax.swing.JSeparator();
        lblUsername1 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        separatorLine6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1500, 1400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signinFormPanel.setBackground(new java.awt.Color(0, 0, 0));
        signinFormPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Optima", 3, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("ROLE");
        signinFormPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("Optima", 3, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("PASSWORD");
        signinFormPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        separatorLine2.setForeground(new java.awt.Color(255, 255, 255));
        signinFormPanel.add(separatorLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 20));

        txtPassword.setBackground(new java.awt.Color(0, 0, 51));
        txtPassword.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("password");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        signinFormPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 300, 30));

        txtUsername.setBackground(new java.awt.Color(0, 0, 51));
        txtUsername.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        txtUsername.setText("Enter Username");
        txtUsername.setBorder(null);
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        signinFormPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 300, 30));

        separatorLine4.setForeground(new java.awt.Color(255, 255, 255));
        signinFormPanel.add(separatorLine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 300, 10));

        lblUsername1.setFont(new java.awt.Font("Optima", 3, 16)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("USERNAME");
        signinFormPanel.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SysAdmin", "CustomerService", "Customer", "Nutritionist", "NutritionSupplier", "PharmaSupplier", "FitnessTrainer", "Therapist", "RehabCenterMgr", "Recruiter", "SportsBrandSupplier" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        signinFormPanel.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 30));

        btnRegister.setText("New Here? Register");
        btnRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        signinFormPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 209, 40));

        btnSignIn.setText("Sign in");
        btnSignIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        signinFormPanel.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 313, 209, 40));

        separatorLine6.setForeground(new java.awt.Color(255, 255, 255));
        signinFormPanel.add(separatorLine6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 300, 10));

        add(signinFormPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 380, 450));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home6.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        UI.SuperAdminRole.RegisterJPanel rejpl = new UI.SuperAdminRole.RegisterJPanel(splitPane,system);
        splitPane.setRightComponent(rejpl);
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        
        String userName = txtUsername.getText();
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
        
        Enterprise inEnterprise=null;
        Organization inOrganization=null;
        //String role=userAccount.getRole().type.toString();
        if(userAccount==null)
        {
        for(Organization organization: system.getOrganizationDirectory().getOrganizationList())
        {
            userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
            if(userAccount!=null)
            {
                inOrganization=organization;
                break;
            }
            
            
        }}

        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(EnterpriseNetwork network:system.getNetworkList()){
                //Step 2.a: check against each enterprise
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                            userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if(userAccount!=null){
                                inEnterprise=enterprise;
                                inOrganization=organization;
                                break;
                            }
                        }
                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inOrganization!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }
        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        if (!chkTerms.isSelected()){
//            JOptionPane.showMessageDialog(null, "Please agree to the terms of service", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        else{
            //set visibility for panels
            //            signinPanel.setVisible(false);
            //            signoutPanel.setVisible(true);
            //            cardPanel.setVisible(true);
            //set visibility for icons
            //            exiticon.setVisible(false);
            //            iconlogout.setVisible(true);
            //set cardlayout panel to display necessary
            //CardLayout layout=(CardLayout) WelcomeCard.getLayout();
            splitPane.setRightComponent(userAccount.getRole().createWorkArea(splitPane, userAccount, inOrganization, inEnterprise, system));
            //WelcomeCard.add("workArea", userAccount.getRole().createWorkArea(WelcomeCard, userAccount, inOrganization, inEnterprise, system));
            //layout.next(WelcomeCard);
    }//GEN-LAST:event_btnSignInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JSeparator separatorLine2;
    private javax.swing.JSeparator separatorLine4;
    private javax.swing.JSeparator separatorLine6;
    private javax.swing.JPanel signinFormPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
