/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise.PharmacyMgrRole;

import Business.Business.EcoSystem;
import Business.Customer.Customer;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PharmaSupplierOrganization;
import Business.UserAccount.UserAccount;
import UI.Welcome.SignInJPanel;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author tanvi
 */
public class PharmaSupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmaSupplierWorkAreaJPanel
     */
    JSplitPane splitPane;
    EcoSystem system;
    Organization supplier;
    Enterprise enterprise;
    UserAccount account;
    //PharmaSupplierOrganization supplier;
    //Employee employee;
    //Customer customer;
    Component previousScreen;

    public PharmaSupplierWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization supplier, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.system = system;
        this.enterprise = enterprise;
        this.account=account;
        this.supplier= supplier;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddProducts = new javax.swing.JButton();
        btnManageProducts = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnManageCustomers = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddProducts.setBackground(new java.awt.Color(102, 153, 255));
        btnAddProducts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProducts.setText("Add Products");
        btnAddProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddProducts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAddProducts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAddProducts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageProducts.setBackground(new java.awt.Color(102, 153, 255));
        btnManageProducts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProducts.setText("Manage Products");
        btnManageProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProducts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProducts.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProducts.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductsActionPerformed(evt);
            }
        });

        btnMyProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnMyProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProfile.setText("My Profile");
        btnMyProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMyProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnManageCustomers.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCustomers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCustomers.setText("Manage Customers");
        btnManageCustomers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCustomers.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCustomers.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageCustomers.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharma Supplier");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pharma3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        AddPharmacyProductsJPanel addPharmacyProductsJPanel = new AddPharmacyProductsJPanel((PharmaSupplierOrganization) supplier, splitPane,account, enterprise, system);
        splitPane.setRightComponent(addPharmacyProductsJPanel);
    }//GEN-LAST:event_btnAddProductsIdentifyResourceAssetsActionPerformed

    private void btnManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductsActionPerformed
        // TODO add your handling code here:

        ManagePharmacyProductsJPanel managePharmacyProductsJPanel = new ManagePharmacyProductsJPanel((PharmaSupplierOrganization)supplier, splitPane,account, enterprise, system);
        splitPane.setRightComponent(managePharmacyProductsJPanel);
    }//GEN-LAST:event_btnManageProductsActionPerformed

    private void btnMyProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileIdentifyEventsActionPerformed
        // TODO add your handling code here:
        Employee employee=account.getEmployee();
        PharmaProfileJPanel pharmaProfileJPanel = new PharmaProfileJPanel((PharmaSupplierOrganization)supplier, splitPane,account, enterprise, system,employee);
        splitPane.setRightComponent(pharmaProfileJPanel);
    }//GEN-LAST:event_btnMyProfileIdentifyEventsActionPerformed

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
//        // TODO add your handling code here:
//        ManageCustomersJPanel manageCustomersJPanel = new ManageCustomersJPanel(supplier, splitPane,account, enterprise, system);
//        //System.out.println(supplier.getName());
//        splitPane.setRightComponent(manageCustomersJPanel);
        
        ManageCustomersJPanel manageCustomersJPanel = new ManageCustomersJPanel((PharmaSupplierOrganization)supplier, splitPane, account, enterprise, system);
    splitPane.setRightComponent(manageCustomersJPanel);

    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        SignInJPanel signInJPanel = new SignInJPanel(splitPane, system);
        splitPane.setRightComponent(signInJPanel);

    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProducts;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManageProducts;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
