/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.StudentRoleWorkResp01;

import Business.Business;
import Business.Course.CourseLoad;
import Business.Course.CourseLoadDirectory;
import Business.Course.CourseOfferDirectory;
import Business.Course.Transcript;
import Business.Profiles.StudentProfile;
import Business.Profiles.ThirdPartyApproval;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author palsa
 */
public class GradAuditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GradAuditJPanel
     */
    StudentProfile studentprofile;
    CourseLoadDirectory courseloaddirectory;
    JPanel CardSequencePanel;
    Business business;
    CourseOfferDirectory courseofferdirectory;
    int selectedRow;
    JSplitPane jSplitPane;
    ThirdPartyApproval tpa;
    public GradAuditJPanel(Business bz, JPanel jp, CourseOfferDirectory courseofferdirectory, CourseLoadDirectory courseloaddirectory, StudentProfile studentprofile, JSplitPane jSplitPane, ThirdPartyApproval tpa) {
        initComponents();
        this.studentprofile=studentprofile;
        this.courseloaddirectory=courseloaddirectory;
        CardSequencePanel = jp;
        this.business = bz;
        this.courseofferdirectory=courseofferdirectory;
        this.jSplitPane=jSplitPane;
        this.tpa=tpa;
        txtReqStatus.setText(studentprofile.getTranscript().getGradStatus());
        populateTable();

    }
    
    public void populateTable()
    {
        System.out.println(studentprofile.getTranscript().gettranscript());
        DefaultTableModel searchModel=(DefaultTableModel)tblCourseWork.getModel();
        searchModel.setRowCount(0);
        for (CourseLoad cl: studentprofile.getTranscript().gettranscript())
            {
                
                Object row[]=new Object[5];
                row[0]=cl;
                row[1]=cl.getCourseOffer().getCrn();
                row[2]=cl.getCourseOffer().getCourse().getCourseName();
                row[3]=cl.getCourseOffer().getCourse().getCredit();
                row[4]=cl.getGrade();

                searchModel.addRow(row); 
                       
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseWork = new javax.swing.JTable();
        lbReqStatus = new javax.swing.JLabel();
        txtReqStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnReadyGrad = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnReadyGrad1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Track your Graduation!");

        tblCourseWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Progress", "CRN", "Course Name ", "Credits", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tblCourseWork);

        lbReqStatus.setText("Current Status:");

        txtReqStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReqStatusActionPerformed(evt);
            }
        });

        jLabel3.setText("Print Degree");

        btnReadyGrad.setBackground(new java.awt.Color(102, 153, 255));
        btnReadyGrad.setForeground(new java.awt.Color(255, 255, 255));
        btnReadyGrad.setText("Refresh status");
        btnReadyGrad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReadyGrad.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReadyGrad.setMinimumSize(new java.awt.Dimension(20, 23));
        btnReadyGrad.setPreferredSize(new java.awt.Dimension(240, 30));
        btnReadyGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyGradIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(20, 23));
        btnBack.setPreferredSize(new java.awt.Dimension(240, 30));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnReadyGrad1.setBackground(new java.awt.Color(102, 153, 255));
        btnReadyGrad1.setForeground(new java.awt.Color(255, 255, 255));
        btnReadyGrad1.setText("Ready to Graduate");
        btnReadyGrad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReadyGrad1.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReadyGrad1.setMinimumSize(new java.awt.Dimension(20, 23));
        btnReadyGrad1.setPreferredSize(new java.awt.Dimension(240, 30));
        btnReadyGrad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyGrad1IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbReqStatus)
                .addGap(18, 18, 18)
                .addComponent(txtReqStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReadyGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReadyGrad1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnReadyGrad1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReqStatus)
                    .addComponent(txtReqStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReadyGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtReqStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReqStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqStatusActionPerformed

    private void btnReadyGradIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyGradIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReadyGradIdentifyResourceAssetsActionPerformed

    private void btnBackIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        StudentWorkAreaJPanel studentworkarea = new StudentWorkAreaJPanel(business, studentprofile, this, courseofferdirectory, jSplitPane, courseloaddirectory,tpa);
        jSplitPane.setRightComponent(studentworkarea);
    }//GEN-LAST:event_btnBackIdentifyResourceAssetsActionPerformed

    private void btnReadyGrad1IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyGrad1IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        txtReqStatus.setEditable(false);

        int ctr=0;
        for (CourseLoad cl: courseloaddirectory.getCourseloadlist())
        {
            if(cl.getStudentProfile().getPerson().getPersonId().equals(studentprofile.getPerson().getPersonId()) && cl.getProgressStatus().equals("Completed"))
            {
                ctr++;
            }
        }
        
        if (ctr==8)
        {
            //Transcript t=studentprofile.getTranscript();
            tpa.pendingApproval(studentprofile);   
            JOptionPane.showMessageDialog(this, "Request sent to Third Party for approval. Please keep a track on the status", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtReqStatus.setText(studentprofile.getTranscript().getGradStatus());       
        
        }

        else
        JOptionPane.showMessageDialog(this, "Sorry! You are not eligible for graduation. You must complete 8 courses to be eligible. Please review your course load", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnReadyGrad1IdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReadyGrad;
    private javax.swing.JButton btnReadyGrad1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbReqStatus;
    private javax.swing.JTable tblCourseWork;
    private javax.swing.JTextField txtReqStatus;
    // End of variables declaration//GEN-END:variables
}
