/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.EmployerRole;

import Business.Profiles.EmployerProfile;
import Business.Profiles.ThirdPartyApproval;
import Business.Profiles.ThirdPartyProfile;
import UserInterface.WorkAreas.EmployerRole.EmployerRoleWorkResp.FresherRecruitmentJPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author tanvi
 */
public class EmployerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployerWorkAreaJPanel
     */
    JSplitPane jsplitPane;
    EmployerProfile ep;
    ThirdPartyApproval tpa;
    public EmployerWorkAreaJPanel(JSplitPane jsplitPane, EmployerProfile ep, ThirdPartyApproval tpa) {
        initComponents();
        this.jsplitPane=jsplitPane;
        this.tpa=tpa;
        this.ep=ep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecruitment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnRecruitment.setBackground(new java.awt.Color(102, 153, 255));
        btnRecruitment.setForeground(new java.awt.Color(255, 255, 255));
        btnRecruitment.setText("Fresher Recruitment");
        btnRecruitment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRecruitment.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRecruitment.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRecruitment.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRecruitment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecruitmentActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employer Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(btnRecruitment, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(btnRecruitment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecruitmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecruitmentActionPerformed
        // TODO add your handling code here:
        
        FresherRecruitmentJPanel fresherrecruitment=new FresherRecruitmentJPanel(jsplitPane, tpa, ep);
        jsplitPane.setRightComponent(fresherrecruitment);

    }//GEN-LAST:event_btnRecruitmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecruitment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
