/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp;

import Business.Course.CourseDirectory;
import Business.Course.CourseLoadDirectory;
import Business.Course.CourseOffer;
import Business.Course.CourseOfferDirectory;
import Business.Profiles.FacultyProfile;
import java.awt.Component;
import java.awt.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author tanvi
 */
public class FacultyUpdateCourseJPanel extends javax.swing.JPanel {

    Component previousScreen;
    JSplitPane splitPane;
    CourseOffer courseOffer;
    CourseDirectory cd;
    CourseOfferDirectory cod;
    FacultyProfile f;
    CourseLoadDirectory courseLoadDirectory;

    /**
     * Creates new form FacultyUpdateCourseJPanel
     */
    public FacultyUpdateCourseJPanel(Component previousScreen, JSplitPane splitPane, CourseOffer courseOffer, CourseDirectory cd, CourseOfferDirectory cod, FacultyProfile f, CourseLoadDirectory courseLoadDirectory) {
        this.previousScreen = previousScreen;
        this.splitPane = splitPane;
        this.courseOffer = courseOffer;
        this.cd = cd;
        this.cod = cod;
        this.f = f;
        this.courseLoadDirectory=courseLoadDirectory;
        initComponents();

        txtUpdateCourseID.setText(String.valueOf(courseOffer.getCrn()));
        txtUpdateCourseName.setText(courseOffer.getCourse().getCourseName());
        txtUpdateCourseDescription.setText(courseOffer.getCourse().getDescription());
        txtUpdateCourseCredits.setText(String.valueOf(courseOffer.getCourse().getCredit()));
        txtUpdateCourseTerm.setText(courseOffer.getTerm());
        txtUpdateCourseYear.setText(String.valueOf(courseOffer.getYear()));
        txtUpdateCourseLanguage.setText(courseOffer.getCourse().getLanguage());

        String schedule = courseOffer.getSchedule();

        Map<String, ArrayList<String>> scheduleMap = new HashMap<>();
        String[] parts = schedule.split(" ");

        { // This code decodes schedule from single string to each daywise strings
            String currentDay = null;
            ArrayList<String> currentSchedule = new ArrayList<>();

            // Iterate through the parts and extract day and time information
            for (String part : parts) {
                if (part.equals("Monday") || part.equals("Tuesday") || part.equals("Wednesday") || part.equals("Thursday") || part.equals("Friday") || part.equals("Saturday")) {
                    if (currentDay != null) {
                        scheduleMap.put(currentDay, currentSchedule);
                    }
                    currentDay = part;
                    currentSchedule = new ArrayList<>();
                } else {
                    currentSchedule.add(part);
                }
            }

// Add the last day's schedule
            if (currentDay != null) {
                scheduleMap.put(currentDay, currentSchedule);
            }

        }

// Access individual variables for each day
        txtUpdateMondaySchedule.setText(String.join(" ", scheduleMap.getOrDefault("Monday", new ArrayList<>())));
        txtUpdateTuesdaySchedule.setText(String.join(" ", scheduleMap.getOrDefault("Tuesday", new ArrayList<>())));
        txtUpdateCourseWednesday.setText(String.join(" ", scheduleMap.getOrDefault("Wednesday", new ArrayList<>())));
        txtUpdateCourseThursday.setText(String.join(" ", scheduleMap.getOrDefault("Thursday", new ArrayList<>())));
        txtUpdateCourseFriday.setText(String.join(" ", scheduleMap.getOrDefault("Friday", new ArrayList<>())));
        txtUpdateCourseSaturday.setText(String.join(" ", scheduleMap.getOrDefault("Saturday", new ArrayList<>())));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitleAddCourse = new javax.swing.JLabel();
        txtUpdateCourseYear = new javax.swing.JTextField();
        lblUpdateCourseName = new javax.swing.JLabel();
        lblUpdateCourseDescription = new javax.swing.JLabel();
        lblUpdateCourseYear = new javax.swing.JLabel();
        lblUpdateCourseCredits = new javax.swing.JLabel();
        lblUpdateCourseTerm = new javax.swing.JLabel();
        txtUpdateCourseName = new javax.swing.JTextField();
        txtUpdateCourseDescription = new javax.swing.JTextField();
        txtUpdateCourseCredits = new javax.swing.JTextField();
        txtUpdateCourseTerm = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtUpdateCourseLanguage = new javax.swing.JTextField();
        lblUpdateCourseLanguage = new javax.swing.JLabel();
        lblUpdateCourseYear1 = new javax.swing.JLabel();
        txtUpdateMondaySchedule = new javax.swing.JTextField();
        txtUpdateCourseWednesday = new javax.swing.JTextField();
        txtUpdateTuesdaySchedule = new javax.swing.JTextField();
        txtUpdateCourseThursday = new javax.swing.JTextField();
        txtUpdateCourseSaturday = new javax.swing.JTextField();
        txtUpdateCourseFriday = new javax.swing.JTextField();
        lblUpdateCourseID = new javax.swing.JLabel();
        txtUpdateCourseID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        lbltitleAddCourse.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbltitleAddCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleAddCourse.setText("Update course");

        txtUpdateCourseYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseYearActionPerformed(evt);
            }
        });

        lblUpdateCourseName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUpdateCourseName.setText("Course Name:");

        lblUpdateCourseDescription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUpdateCourseDescription.setText("Description:");

        lblUpdateCourseYear.setText("Year:");

        lblUpdateCourseCredits.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUpdateCourseCredits.setText("Credits:");

        lblUpdateCourseTerm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUpdateCourseTerm.setText("Term:");

        txtUpdateCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseNameActionPerformed(evt);
            }
        });

        txtUpdateCourseDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseDescriptionActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(20, 20));
        btnBack.setPreferredSize(new java.awt.Dimension(240, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtUpdateCourseLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseLanguageActionPerformed(evt);
            }
        });

        lblUpdateCourseLanguage.setText("Language:");

        lblUpdateCourseYear1.setText("Course Schedule :");

        txtUpdateMondaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateMondayScheduleActionPerformed(evt);
            }
        });

        txtUpdateCourseWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseWednesdayActionPerformed(evt);
            }
        });

        txtUpdateTuesdaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateTuesdayScheduleActionPerformed(evt);
            }
        });

        txtUpdateCourseThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseThursdayActionPerformed(evt);
            }
        });

        txtUpdateCourseSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseSaturdayActionPerformed(evt);
            }
        });

        txtUpdateCourseFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseFridayActionPerformed(evt);
            }
        });

        lblUpdateCourseID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUpdateCourseID.setText(" CRN:");

        txtUpdateCourseID.setEditable(false);
        txtUpdateCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCourseIDActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(102, 153, 255));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSave.setMinimumSize(new java.awt.Dimension(20, 20));
        btnSave.setPreferredSize(new java.awt.Dimension(240, 25));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Monday");

        jLabel2.setText("Tuesday");

        jLabel3.setText("Wednesday");

        jLabel4.setText("Thursday");

        jLabel5.setText("Friday");

        jLabel6.setText("Saturday");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitleAddCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUpdateCourseName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCourseDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCourseCredits, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCourseTerm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCourseYear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCourseLanguage, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCourseYear1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCourseID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpdateCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateCourseCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateCourseTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateCourseYear, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateCourseLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUpdateMondaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtUpdateCourseSaturday, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUpdateCourseFriday, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUpdateCourseThursday, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUpdateCourseWednesday, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUpdateTuesdaySchedule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltitleAddCourse)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCourseID)
                    .addComponent(txtUpdateCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCourseName)
                    .addComponent(txtUpdateCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCourseDescription)
                    .addComponent(txtUpdateCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCourseCredits)
                    .addComponent(txtUpdateCourseCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCourseTerm)
                    .addComponent(txtUpdateCourseTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCourseYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateCourseYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCourseLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateCourseLanguage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCourseYear1)
                    .addComponent(txtUpdateMondaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateTuesdaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCourseWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCourseThursday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCourseFriday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCourseSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUpdateCourseYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseYearActionPerformed

    private void txtUpdateCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseNameActionPerformed

    private void txtUpdateCourseDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseDescriptionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FacultyViewCourseJPanel facultyviewcourse = new FacultyViewCourseJPanel(previousScreen, splitPane, f, cd, cod, courseLoadDirectory);
        splitPane.setRightComponent(facultyviewcourse);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUpdateCourseLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseLanguageActionPerformed

    private void txtUpdateMondayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateMondayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateMondayScheduleActionPerformed

    private void txtUpdateCourseWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseWednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseWednesdayActionPerformed

    private void txtUpdateTuesdayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateTuesdayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateTuesdayScheduleActionPerformed

    private void txtUpdateCourseThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseThursdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseThursdayActionPerformed

    private void txtUpdateCourseSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseSaturdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseSaturdayActionPerformed

    private void txtUpdateCourseFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseFridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseFridayActionPerformed

    private void txtUpdateCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCourseIDActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtUpdateCourseID.getText().isEmpty() || txtUpdateCourseName.getText().isEmpty()
                || txtUpdateCourseDescription.getText().isEmpty() || txtUpdateCourseCredits.getText().isEmpty()
                || txtUpdateCourseTerm.getText().isEmpty() || txtUpdateCourseYear.getText().isEmpty()
                || txtUpdateCourseLanguage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all values.");
            return;
        }

        if (!txtUpdateCourseID.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Course ID must be a numeric value.");
            return;
        }

        if (!txtUpdateCourseCredits.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Credits must be a numeric value.");
            return;
        }

        if (!txtUpdateCourseYear.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Year must be a numeric value.");
            return;
        }

        courseOffer.setCrn(Integer.parseInt(txtUpdateCourseID.getText()));
        courseOffer.setTerm(txtUpdateCourseTerm.getText());
        courseOffer.getCourse().setCourseName(txtUpdateCourseName.getText());
        courseOffer.getCourse().setDescription(txtUpdateCourseDescription.getText());
        courseOffer.getCourse().setCredit(Float.parseFloat(txtUpdateCourseCredits.getText()));
        courseOffer.getCourse().setLanguage(txtUpdateCourseLanguage.getText());
        courseOffer.setYear(Integer.parseInt(txtUpdateCourseYear.getText()));

String schedule = "";
 if (!txtUpdateMondaySchedule.getText().isBlank()) {
            schedule += "Monday " +  txtUpdateMondaySchedule.getText() + " ";
        }
        if (!txtUpdateTuesdaySchedule.getText().isBlank()) {
            schedule += "Tuesday " + txtUpdateTuesdaySchedule.getText() + " ";
        }
        if (!txtUpdateCourseWednesday.getText().isBlank()) {
            schedule += "Wednesday " + txtUpdateCourseWednesday.getText() + " ";
        }
        if (!txtUpdateCourseThursday.getText().isBlank()) {
            schedule += "Thursday " + txtUpdateCourseThursday.getText() + " ";
        }
        if (!txtUpdateCourseFriday.getText().isBlank()) {
            schedule += "Friday " + txtUpdateCourseFriday.getText() + " ";
        }
        if (!txtUpdateCourseSaturday.getText().isBlank()) {
            schedule += "Saturday " + txtUpdateCourseSaturday.getText() + " ";
        }
        

        courseOffer.setSchedule(schedule);
        JOptionPane.showMessageDialog(this, "Course information is updated.");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblUpdateCourseCredits;
    private javax.swing.JLabel lblUpdateCourseDescription;
    private javax.swing.JLabel lblUpdateCourseID;
    private javax.swing.JLabel lblUpdateCourseLanguage;
    private javax.swing.JLabel lblUpdateCourseName;
    private javax.swing.JLabel lblUpdateCourseTerm;
    private javax.swing.JLabel lblUpdateCourseYear;
    private javax.swing.JLabel lblUpdateCourseYear1;
    private javax.swing.JLabel lbltitleAddCourse;
    private javax.swing.JTextField txtUpdateCourseCredits;
    private javax.swing.JTextField txtUpdateCourseDescription;
    private javax.swing.JTextField txtUpdateCourseFriday;
    private javax.swing.JTextField txtUpdateCourseID;
    private javax.swing.JTextField txtUpdateCourseLanguage;
    private javax.swing.JTextField txtUpdateCourseName;
    private javax.swing.JTextField txtUpdateCourseSaturday;
    private javax.swing.JTextField txtUpdateCourseTerm;
    private javax.swing.JTextField txtUpdateCourseThursday;
    private javax.swing.JTextField txtUpdateCourseWednesday;
    private javax.swing.JTextField txtUpdateCourseYear;
    private javax.swing.JTextField txtUpdateMondaySchedule;
    private javax.swing.JTextField txtUpdateTuesdaySchedule;
    // End of variables declaration//GEN-END:variables
}
