/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp;

import Business.Course.Course;
import Business.Course.CourseDirectory;
import Business.Course.CourseOffer;
import Business.Course.CourseOfferDirectory;
import Business.Profiles.FacultyProfile;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author tanvi
 */
public class FacultyAddCourseJPanel extends javax.swing.JPanel {

    Component previousScreen;
    JSplitPane splitPane;
    FacultyProfile facultyProfile;
    CourseDirectory courseDirectory;
    CourseOfferDirectory courseOfferDirectory;
    
    /**
     * Creates new form FacultyAddCourseJPanel
     */
    public FacultyAddCourseJPanel(Component previousScreen, JSplitPane splitPane, FacultyProfile f, CourseDirectory cd, CourseOfferDirectory cod) {
        initComponents();
        this.previousScreen = previousScreen;
        this.splitPane = splitPane;
        this.facultyProfile = f;
        this.courseDirectory = cd;
        this.courseOfferDirectory = cod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitleAddCourse = new javax.swing.JLabel();
        txtAddCourseYear = new javax.swing.JTextField();
        lblAddCourseName = new javax.swing.JLabel();
        lblAddCourseDescription = new javax.swing.JLabel();
        lblAddCourseYear = new javax.swing.JLabel();
        lblAddCourseCredits = new javax.swing.JLabel();
        lblAddCourseTerm = new javax.swing.JLabel();
        txtAddCourseName = new javax.swing.JTextField();
        txtAddCourseDescription = new javax.swing.JTextField();
        txtAddCourseCredits = new javax.swing.JTextField();
        txtAddCourseTerm = new javax.swing.JTextField();
        btnAddCourseSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtAddCourseLanguage = new javax.swing.JTextField();
        lblAddCourseLanguage = new javax.swing.JLabel();
        lblAddCourseYear1 = new javax.swing.JLabel();
        txtMondaySchedule = new javax.swing.JTextField();
        txtWednesdaySchedule = new javax.swing.JTextField();
        txtTuesdaySchedule = new javax.swing.JTextField();
        txtThursdaySchedule = new javax.swing.JTextField();
        txtSaturdaySchedule = new javax.swing.JTextField();
        txtFridaySchedule = new javax.swing.JTextField();
        lblAddCourseID = new javax.swing.JLabel();
        txtAddCourseID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        lbltitleAddCourse.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbltitleAddCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleAddCourse.setText("Add course");

        txtAddCourseYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCourseYearActionPerformed(evt);
            }
        });

        lblAddCourseName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAddCourseName.setText("Course Name:");

        lblAddCourseDescription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAddCourseDescription.setText("Description:");

        lblAddCourseYear.setText("Year:");

        lblAddCourseCredits.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAddCourseCredits.setText("Credits:");

        lblAddCourseTerm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAddCourseTerm.setText("Term:");

        txtAddCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCourseNameActionPerformed(evt);
            }
        });

        txtAddCourseDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCourseDescriptionActionPerformed(evt);
            }
        });

        btnAddCourseSave.setBackground(new java.awt.Color(102, 153, 255));
        btnAddCourseSave.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourseSave.setText("Save");
        btnAddCourseSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddCourseSave.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAddCourseSave.setMinimumSize(new java.awt.Dimension(20, 20));
        btnAddCourseSave.setPreferredSize(new java.awt.Dimension(240, 25));
        btnAddCourseSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(20, 20));
        btnBack.setPreferredSize(new java.awt.Dimension(240, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtAddCourseLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCourseLanguageActionPerformed(evt);
            }
        });

        lblAddCourseLanguage.setText("Language:");

        lblAddCourseYear1.setText("Course Schedule :");

        txtMondaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMondayScheduleActionPerformed(evt);
            }
        });

        txtWednesdaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWednesdayScheduleActionPerformed(evt);
            }
        });

        txtTuesdaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuesdayScheduleActionPerformed(evt);
            }
        });

        txtThursdaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThursdayScheduleActionPerformed(evt);
            }
        });

        txtSaturdaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaturdayScheduleActionPerformed(evt);
            }
        });

        txtFridaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFridayScheduleActionPerformed(evt);
            }
        });

        lblAddCourseID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAddCourseID.setText("CRN:");

        txtAddCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCourseIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Monday");

        jLabel2.setText("Tuesday");

        jLabel3.setText("Wednesday");

        jLabel4.setText("Thursday");

        jLabel5.setText("Friday");

        jLabel6.setText("Saturday");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitleAddCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddCourseName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddCourseDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddCourseCredits, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddCourseTerm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddCourseYear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddCourseLanguage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddCourseYear1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddCourseID, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddCourseCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddCourseTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddCourseYear, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAddCourseSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(169, 169, 169)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMondaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSaturdaySchedule, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFridaySchedule, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtThursdaySchedule, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtWednesdaySchedule, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTuesdaySchedule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtAddCourseLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltitleAddCourse)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCourseID)
                    .addComponent(txtAddCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCourseName)
                    .addComponent(txtAddCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCourseDescription)
                    .addComponent(txtAddCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCourseCredits)
                    .addComponent(txtAddCourseCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCourseTerm)
                    .addComponent(txtAddCourseTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddCourseYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddCourseYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddCourseLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddCourseLanguage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCourseYear1)
                    .addComponent(txtMondaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTuesdaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWednesdaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThursdaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFridaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaturdaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourseSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(458, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddCourseYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCourseYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCourseYearActionPerformed

    private void txtAddCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCourseNameActionPerformed

    private void txtAddCourseDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCourseDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCourseDescriptionActionPerformed

    private void btnAddCourseSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseSaveActionPerformed
        // TODO add your handling code here:

        if (txtAddCourseID.getText().isEmpty() || txtAddCourseName.getText().isEmpty()
                || txtAddCourseDescription.getText().isEmpty() || txtAddCourseCredits.getText().isEmpty()
                || txtAddCourseTerm.getText().isEmpty() || txtAddCourseYear.getText().isEmpty()
                || txtAddCourseLanguage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.");
            return;
        }

        if (!txtAddCourseID.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Course ID must be a numeric value.");
            return;
        }

        if (!txtAddCourseCredits.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Credits must be a numeric value.");
            return;
        }

        if (!txtAddCourseYear.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Year must be a numeric value.");
            return;
        }

        int courseID = Integer.parseInt(txtAddCourseID.getText());
        String courseName = txtAddCourseName.getText();
        String courseDescription = txtAddCourseDescription.getText();
        Float credits = Float.parseFloat(txtAddCourseCredits.getText());
        String language = txtAddCourseLanguage.getText();

        Course existingCourse = courseDirectory.findCourse(courseID);
        if (existingCourse != null) {
            JOptionPane.showMessageDialog(this, "Course already exists.");
            return;
        }

        Course course = courseDirectory.newCourse(courseID, courseName, courseDescription, credits, language);

        String schedule = "";
        if (!txtMondaySchedule.getText().isBlank()) {
            schedule += "Monday " +  txtMondaySchedule.getText() + " ";
        }
        if (!txtTuesdaySchedule.getText().isBlank()) {
            schedule += "Tuesday " + txtTuesdaySchedule.getText() + " ";
        }
        if (!txtWednesdaySchedule.getText().isBlank()) {
            schedule += "Wednesday " + txtWednesdaySchedule.getText() + " ";
        }
        if (!txtThursdaySchedule.getText().isBlank()) {
            schedule += "Thursday " + txtThursdaySchedule.getText() + " ";
        }
        if (!txtFridaySchedule.getText().isBlank()) {
            schedule += "Friday " + txtFridaySchedule.getText() + " ";
        }
        if (!txtSaturdaySchedule.getText().isBlank()) {
            schedule += "Saturday " + txtSaturdaySchedule.getText() + " ";
        }
        
        int year = Integer.parseInt(txtAddCourseYear.getText());
        String term = txtAddCourseTerm.getText();
        
        CourseOffer co = courseOfferDirectory.newCourseOffer(courseID,facultyProfile, term, year, course, schedule);
        
        JOptionPane.showMessageDialog(this, "Course information is added.");
    }//GEN-LAST:event_btnAddCourseSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        splitPane.setRightComponent(previousScreen);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAddCourseLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCourseLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCourseLanguageActionPerformed

    private void txtMondayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMondayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMondayScheduleActionPerformed

    private void txtWednesdayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWednesdayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWednesdayScheduleActionPerformed

    private void txtTuesdayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuesdayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuesdayScheduleActionPerformed

    private void txtThursdayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThursdayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThursdayScheduleActionPerformed

    private void txtSaturdayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaturdayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaturdayScheduleActionPerformed

    private void txtFridayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFridayScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFridayScheduleActionPerformed

    private void txtAddCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCourseIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourseSave;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAddCourseCredits;
    private javax.swing.JLabel lblAddCourseDescription;
    private javax.swing.JLabel lblAddCourseID;
    private javax.swing.JLabel lblAddCourseLanguage;
    private javax.swing.JLabel lblAddCourseName;
    private javax.swing.JLabel lblAddCourseTerm;
    private javax.swing.JLabel lblAddCourseYear;
    private javax.swing.JLabel lblAddCourseYear1;
    private javax.swing.JLabel lbltitleAddCourse;
    private javax.swing.JTextField txtAddCourseCredits;
    private javax.swing.JTextField txtAddCourseDescription;
    private javax.swing.JTextField txtAddCourseID;
    private javax.swing.JTextField txtAddCourseLanguage;
    private javax.swing.JTextField txtAddCourseName;
    private javax.swing.JTextField txtAddCourseTerm;
    private javax.swing.JTextField txtAddCourseYear;
    private javax.swing.JTextField txtFridaySchedule;
    private javax.swing.JTextField txtMondaySchedule;
    private javax.swing.JTextField txtSaturdaySchedule;
    private javax.swing.JTextField txtThursdaySchedule;
    private javax.swing.JTextField txtTuesdaySchedule;
    private javax.swing.JTextField txtWednesdaySchedule;
    // End of variables declaration//GEN-END:variables
}
