/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp;

import Business.Business;
import Business.Course.CourseDirectory;
import Business.Course.CourseLoad;
import Business.Course.CourseLoadDirectory;
import Business.Course.CourseOfferDirectory;
import Business.Profiles.FacultyProfile;
import UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanvi
 */
public class FacultyManageStudentProfileJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    JSplitPane splitPane;
    FacultyProfile facultyProfile;
    CourseDirectory cd;
    CourseOfferDirectory cod;
    CourseLoadDirectory courseLoadDirectory;
    CourseLoad courseLoad;

    /**
     * Creates new form ManageStudentProfileJPanel
     */
    public FacultyManageStudentProfileJPanel(JSplitPane splitPane, FacultyProfile f, CourseDirectory cd, CourseOfferDirectory cod, CourseLoadDirectory courseLoadDirectory) {

        this.splitPane = splitPane;
        this.cd = cd;
        this.cod = cod;
        this.facultyProfile=f;
        this.courseLoadDirectory=courseLoadDirectory;

        initComponents();
        populateTable();
    }

    private void populateTable() {
        {
            DefaultTableModel searchModel = (DefaultTableModel) tblListStudent.getModel();
            searchModel.setRowCount(0);

            for (CourseLoad courseload : courseLoadDirectory.getCourseLoadFacultyId(facultyProfile.getFacultyId())) {
                Object row[] = new Object[7];
                row[0] = courseload.getStudentProfile().getStudentId();
                row[1] = courseload.getStudentProfile().getPerson().getName();
                row[2] = courseload.getCourseOffer().getCrn();
                row[3] = courseload.getCourseOffer().getCourse().getCourseName();
                row[4] = courseload.getCourseOffer().getTerm();
                row[5] = courseload.getCourseOffer().getYear();
                row[6] = courseload;
                searchModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleManageStudentProfile = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListStudent = new javax.swing.JTable();
        lblManageStudentProfileYear = new javax.swing.JLabel();
        txtManageStudentProfileStudentID = new javax.swing.JTextField();
        lblManageStudentProfileCourseName = new javax.swing.JLabel();
        txtManageStudentProfileName = new javax.swing.JTextField();
        txtManageStudentProfileCRN = new javax.swing.JTextField();
        txtManageStudentProfileYear = new javax.swing.JTextField();
        txtManageStudentProfileCourseName = new javax.swing.JTextField();
        lblManageStudentName = new javax.swing.JLabel();
        txtManageStudentProfileTerm = new javax.swing.JTextField();
        lblManageStudentProfileStudentID = new javax.swing.JLabel();
        lblManageStudentProfileCRN = new javax.swing.JLabel();
        lblManageStudentProfileTerm = new javax.swing.JLabel();
        BtnGrade = new javax.swing.JButton();
        txtManageStudentProfileGrade = new javax.swing.JTextField();
        lblManageStudentProfileGrade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeedback = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        lblTitleManageStudentProfile.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitleManageStudentProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleManageStudentProfile.setText("Manage Student Profile");

        btnView.setBackground(new java.awt.Color(102, 153, 255));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.setMaximumSize(new java.awt.Dimension(200, 40));
        btnView.setMinimumSize(new java.awt.Dimension(20, 20));
        btnView.setPreferredSize(new java.awt.Dimension(240, 25));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(20, 20));
        btnBack.setPreferredSize(new java.awt.Dimension(240, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblListStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "CRN", "Course Name", "Term", "Year", "Progress Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListStudent.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblListStudent);

        lblManageStudentProfileYear.setText("Year:");

        txtManageStudentProfileStudentID.setEditable(false);
        txtManageStudentProfileStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageStudentProfileStudentIDActionPerformed(evt);
            }
        });

        lblManageStudentProfileCourseName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblManageStudentProfileCourseName.setText("Course Name:");

        txtManageStudentProfileName.setEditable(false);
        txtManageStudentProfileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageStudentProfileNameActionPerformed(evt);
            }
        });

        txtManageStudentProfileCRN.setEditable(false);
        txtManageStudentProfileCRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageStudentProfileCRNActionPerformed(evt);
            }
        });

        txtManageStudentProfileYear.setEditable(false);
        txtManageStudentProfileYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageStudentProfileYearActionPerformed(evt);
            }
        });

        txtManageStudentProfileCourseName.setEditable(false);

        lblManageStudentName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblManageStudentName.setText("Student Name");

        txtManageStudentProfileTerm.setEditable(false);

        lblManageStudentProfileStudentID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblManageStudentProfileStudentID.setText(" Student ID:");

        lblManageStudentProfileCRN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblManageStudentProfileCRN.setText("CRN:");

        lblManageStudentProfileTerm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblManageStudentProfileTerm.setText("Term:");

        BtnGrade.setBackground(new java.awt.Color(102, 153, 255));
        BtnGrade.setForeground(new java.awt.Color(255, 255, 255));
        BtnGrade.setText("Save Grade");
        BtnGrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGrade.setMaximumSize(new java.awt.Dimension(200, 40));
        BtnGrade.setMinimumSize(new java.awt.Dimension(20, 20));
        BtnGrade.setPreferredSize(new java.awt.Dimension(240, 25));
        BtnGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGradeActionPerformed(evt);
            }
        });

        txtManageStudentProfileGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageStudentProfileGradeActionPerformed(evt);
            }
        });

        lblManageStudentProfileGrade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblManageStudentProfileGrade.setText("Grade:");

        txtFeedback.setEditable(false);
        txtFeedback.setColumns(20);
        txtFeedback.setRows(5);
        jScrollPane1.setViewportView(txtFeedback);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Employer Feedback to student:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleManageStudentProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(499, 499, 499)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblManageStudentProfileStudentID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManageStudentProfileYear, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblManageStudentProfileCourseName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblManageStudentProfileTerm, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblManageStudentName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblManageStudentProfileCRN, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtManageStudentProfileStudentID)
                            .addComponent(txtManageStudentProfileName)
                            .addComponent(txtManageStudentProfileCRN)
                            .addComponent(txtManageStudentProfileCourseName)
                            .addComponent(txtManageStudentProfileTerm)
                            .addComponent(txtManageStudentProfileYear, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblManageStudentProfileGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManageStudentProfileGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitleManageStudentProfile)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManageStudentProfileStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManageStudentProfileStudentID)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManageStudentName)
                            .addComponent(txtManageStudentProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManageStudentProfileCRN)
                            .addComponent(txtManageStudentProfileCRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManageStudentProfileCourseName)
                            .addComponent(txtManageStudentProfileCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManageStudentProfileTerm)
                            .addComponent(txtManageStudentProfileTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManageStudentProfileYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManageStudentProfileYear))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManageStudentProfileGrade)
                            .addComponent(txtManageStudentProfileGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblListStudent.getSelectedRow();

        if (selectedRowIndex < 0) {

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        else
        {
        DefaultTableModel model = (DefaultTableModel) tblListStudent.getModel();
        courseLoad = (CourseLoad) model.getValueAt(selectedRowIndex, 6);
        
        if(courseLoad.getStudentProfile().getStatus().equals("Hired") || courseLoad.getStudentProfile().getTranscript().getGradStatus().equals("Graduated"))
        {
            BtnGrade.setEnabled(false);
            txtManageStudentProfileGrade.setText(courseLoad.getGrade());
            txtManageStudentProfileGrade.setEditable(false);
            txtFeedback.setText(courseLoad.getStudentProfile().getFeedback());

        }
        
        txtManageStudentProfileStudentID.setText(String.valueOf(courseLoad.getStudentProfile().getStudentId()));
        txtManageStudentProfileName.setText(courseLoad.getStudentProfile().getPerson().getName());
        txtManageStudentProfileCRN.setText(String.valueOf(courseLoad.getCourseOffer().getCrn()));
        txtManageStudentProfileCourseName.setText(courseLoad.getCourseOffer().getCourse().getCourseName());
        txtManageStudentProfileTerm.setText(courseLoad.getCourseOffer().getTerm());
        txtManageStudentProfileYear.setText(String.valueOf(courseLoad.getCourseOffer().getYear()));
        
        
        }

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FacultyWorkAreaJPanel facultyworkarea = new FacultyWorkAreaJPanel(splitPane, facultyProfile, cd, cod, courseLoadDirectory);
        splitPane.setRightComponent(facultyworkarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtManageStudentProfileStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageStudentProfileStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManageStudentProfileStudentIDActionPerformed

    private void txtManageStudentProfileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageStudentProfileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManageStudentProfileNameActionPerformed

    private void txtManageStudentProfileCRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageStudentProfileCRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManageStudentProfileCRNActionPerformed

    private void txtManageStudentProfileYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageStudentProfileYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManageStudentProfileYearActionPerformed

    private void BtnGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGradeActionPerformed
        // TODO add your handling code here:
        String grade = txtManageStudentProfileGrade.getText();
        String gradePattern = "^[A-Fa-f]$";
        if (grade.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a grade.");
        } else if (!grade.matches(gradePattern)) {
            JOptionPane.showMessageDialog(this, "Invalid grade. Please enter a valid grade (e.g., A, B, C, etc.).");
        } else {
            
            courseLoad.setGrade(txtManageStudentProfileGrade.getText());
            JOptionPane.showMessageDialog(this, "Grades are saved successfully!");
        }

    }//GEN-LAST:event_BtnGradeActionPerformed

    private void txtManageStudentProfileGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageStudentProfileGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManageStudentProfileGradeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGrade;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblManageStudentName;
    private javax.swing.JLabel lblManageStudentProfileCRN;
    private javax.swing.JLabel lblManageStudentProfileCourseName;
    private javax.swing.JLabel lblManageStudentProfileGrade;
    private javax.swing.JLabel lblManageStudentProfileStudentID;
    private javax.swing.JLabel lblManageStudentProfileTerm;
    private javax.swing.JLabel lblManageStudentProfileYear;
    private javax.swing.JLabel lblTitleManageStudentProfile;
    private javax.swing.JTable tblListStudent;
    private javax.swing.JTextArea txtFeedback;
    private javax.swing.JTextField txtManageStudentProfileCRN;
    private javax.swing.JTextField txtManageStudentProfileCourseName;
    private javax.swing.JTextField txtManageStudentProfileGrade;
    private javax.swing.JTextField txtManageStudentProfileName;
    private javax.swing.JTextField txtManageStudentProfileStudentID;
    private javax.swing.JTextField txtManageStudentProfileTerm;
    private javax.swing.JTextField txtManageStudentProfileYear;
    // End of variables declaration//GEN-END:variables
}
