/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp;

import Business.Course.CourseDirectory;
import Business.Course.CourseLoadDirectory;
import Business.Course.CourseOfferDirectory;
import Business.Profiles.FacultyProfile;
import UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import java.awt.Component;
import javax.swing.JSplitPane;

/**
 *
 * @author tanvi
 */
public class FacultyManageCourseJPanel extends javax.swing.JPanel {
    Component previousScreen;
    JSplitPane splitPane;
    FacultyProfile facultyProfile;
    CourseDirectory courseDirectory;
    CourseOfferDirectory courseOfferDirectory;
    CourseLoadDirectory courseLoadDirectory;

    /**
     * Creates new form FacultyManagePersonJPanel
     */
    public FacultyManageCourseJPanel(Component previousScreen,JSplitPane splitPane, FacultyProfile f, CourseDirectory cd, CourseOfferDirectory cod, CourseLoadDirectory courseLoadDirectory) {
        this.previousScreen = previousScreen;
        this.splitPane = splitPane;
        this.facultyProfile = f;
        this.courseDirectory = cd;
        this.courseOfferDirectory = cod;
        this.courseLoadDirectory=courseLoadDirectory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCourse = new javax.swing.JButton();
        btnViewCourse = new javax.swing.JButton();
        lblTitleManageCourse = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        btnAddCourse.setBackground(new java.awt.Color(102, 153, 255));
        btnAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setText("Add Course");
        btnAddCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddCourse.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAddCourse.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAddCourse.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnViewCourse.setBackground(new java.awt.Color(102, 153, 255));
        btnViewCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCourse.setText("View Courses");
        btnViewCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewCourse.setMaximumSize(new java.awt.Dimension(200, 40));
        btnViewCourse.setMinimumSize(new java.awt.Dimension(20, 20));
        btnViewCourse.setPreferredSize(new java.awt.Dimension(240, 25));
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        lblTitleManageCourse.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitleManageCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleManageCourse.setText("Manage courses");

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(20, 20));
        btnBack.setPreferredSize(new java.awt.Dimension(240, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleManageCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 123, Short.MAX_VALUE)
                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 123, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitleManageCourse)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCourseIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        FacultyAddCourseJPanel facultyAddCourseJPanel = new FacultyAddCourseJPanel(this, splitPane, facultyProfile, courseDirectory, courseOfferDirectory);//,courseDirectory
        splitPane.setRightComponent(facultyAddCourseJPanel);

    }//GEN-LAST:event_btnAddCourseIdentifyResourceAssetsActionPerformed

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        // TODO add your handling code here:
        FacultyViewCourseJPanel facultyViewCourseJPanel = new FacultyViewCourseJPanel(this, splitPane, facultyProfile, courseDirectory, courseOfferDirectory, courseLoadDirectory);//,courseDirectory
        splitPane.setRightComponent(facultyViewCourseJPanel);

    }//GEN-LAST:event_btnViewCourseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FacultyWorkAreaJPanel facultyworkarea = new FacultyWorkAreaJPanel(splitPane, facultyProfile, courseDirectory, courseOfferDirectory,courseLoadDirectory);
        splitPane.setRightComponent(facultyworkarea);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "faculty");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JLabel lblTitleManageCourse;
    // End of variables declaration//GEN-END:variables
}
