/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp;

import Business.Business;
import Business.Course.CourseDirectory;
import Business.Course.CourseLoad;
import Business.Course.CourseOffer;
import Business.Course.CourseLoadDirectory;
import Business.Course.CourseOfferDirectory;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanvi
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    JSplitPane splitPane;
    FacultyProfile facultyProfile;
    CourseDirectory cd;
    CourseOfferDirectory cod;
    Component previousScreen;
    CourseLoadDirectory courseLoadDirectory;

    /**
     * Creates new form PerformanceReportsJPanel
     */
    public PerformanceReportsJPanel(JSplitPane splitPane, FacultyProfile f, CourseDirectory cd, CourseOfferDirectory cod,CourseLoadDirectory courseLoadDirectory) {
        //this.previousScreen = previousScreen;
        this.cd = cd;
        this.cod = cod;
        this.splitPane = splitPane;
        this.courseLoadDirectory=courseLoadDirectory;
        this.facultyProfile=f;
        
        
        initComponents();
        populateTable();
    }

    private void populateTable() {
        {
            DefaultTableModel searchModel = (DefaultTableModel) tblPerformanceReport.getModel();
            searchModel.setRowCount(0);

            for (CourseLoad courseload :  courseLoadDirectory.getCourseLoadFacultyId(facultyProfile.getFacultyId())) {
                Object row[] = new Object[7];
                row[0] = courseload.getStudentProfile().getStudentId();
                row[1] = courseload.getStudentProfile().getPerson().getName();
                row[2] = courseload.getCourseOffer().getCrn();
                row[3] = courseload.getCourseOffer().getCourse().getCourseName();
                row[4] = courseload.getCourseOffer().getTerm();
                row[5] = courseload.getCourseOffer().getYear();
                row[6] = courseload.getGrade();
                searchModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitlePerformanceReport = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerformanceReport = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        txtTitlePerformanceReport.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTitlePerformanceReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitlePerformanceReport.setText("Performance Report");

        tblPerformanceReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "CRN", "Course Name", "Term", "Year", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPerformanceReport.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblPerformanceReport);

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(20, 20));
        btnBack.setPreferredSize(new java.awt.Dimension(240, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtTitlePerformanceReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtTitlePerformanceReport)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FacultyWorkAreaJPanel facultyworkarea = new FacultyWorkAreaJPanel(splitPane, facultyProfile, cd, cod,courseLoadDirectory);
        splitPane.setRightComponent(facultyworkarea);
//        splitPane.setRightComponent(previousScreen);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPerformanceReport;
    private javax.swing.JLabel txtTitlePerformanceReport;
    // End of variables declaration//GEN-END:variables
}
